# --- Basic options --- #

title: Roller
title_url: https://chaaz.github.io/roller
description: Characters and Code
author: Charlie Ozinga
show_downloads: false
show_view_on_github: false

github:
  is_project_page: false
  is_user_page: false

theme: jekyll-theme-dinky
